export enum Permission {
  MANAGE_USERS = 'MANAGE_USERS',
  MANAGE_PATIENTS = 'MANAGE_PATIENTS',
  MANAGE_ORDERS = 'MANAGE_ORDERS',
  MANAGE_REPORTS = 'MANAGE_REPORTS',
  MANAGE_BILLING = 'MANAGE_BILLING',
  MANAGE_INSURANCE = 'MANAGE_INSURANCE',
  MANAGE_AUDIT = 'MANAGE_AUDIT',
  MANAGE_NOTIFICATIONS = 'MANAGE_NOTIFICATIONS',
}
