export enum ActionType {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  STATUS_CHANGE = 'STATUS_CHANGE',
  PAYMENT = 'PAYMENT',
  REPORT_VERIFY = 'REPORT_VERIFY',
  CLAIM_SUBMIT = 'CLAIM_SUBMIT',
  OTHER = 'OTHER',
}
