export enum OrderStatus {
  CREATED = 'CREATED',
  PAID = 'PAID',
  SAMPLE_COLLECTED = 'SAMPLE_COLLECTED',
  IN_PROCESS = 'IN_PROCESS',
  VERIFIED = 'VERIFIED',
  RELEASED = 'RELEASED',
  CANCELLED = 'CANCELLED',
}
