export enum Specialization {
  GENERAL_PHYSICIAN = 'GENERAL_PHYSICIAN',
  PATHOLOGIST = 'PATHOLOGIST',
  CARDIOLOGIST = 'CARDIOLOGIST',
  NEUROLOGIST = 'NEUROLOGIST',
  DERMATOLOGIST = 'DERMATOLOGIST',
  PEDIATRICIAN = 'PEDIATRICIAN',
  RADIOLOGIST = 'RADIOLOGIST',
}
